# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Compile Code
      run: mvn -B -e -U -ntp clean compile test-compile
    - name: Code Analysis
      run: >
        mvn -B -e -U -ntp
        org.jacoco:jacoco-maven-plugin:prepare-agent
        package
        org.jacoco:jacoco-maven-plugin:report
        verify
        org.jacoco:jacoco-maven-plugin:check
    - name: SonarCloud Scan
      run: >
        mvn -B -e -ntp sonar:sonar
        -Dsonar.host.url=$SONAR_HOST
        -Dsonar.login=$SONAR_TOKEN
        -Dsonar.organization=supensour
        -Dsonar.verbose=true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST: https://sonarcloud.io
